version: "3.3"
services:
  video-rtsp:
    build:
      context: ./video-rtsp/
    ports:
      - "8554:8554"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    environment:
      frame_height: 1920
      frame_width: 1080
      video_port: 8554
      fps: 30
    privileged: true
    restart: always
  gpsd:
    build:
      context: ./gpsd/
    ports:
      - "2947:2947"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      gpsd_device: /dev/ttyACM0
    privileged: true
    restart: always
  imu-reader:
    build:
      context: ./imu-reader/
    ports:
      - "5000:5000"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true
    restart: always