version: "3.3"
services:
  video-rtsp:
    build:
      context: ./video-rtsp/
    ports:
      - "8554:8554"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    environment:
      frame_height: 1920
      frame_width: 1080
      video_port: 8554
      fps: 30
    privleged: true
  gpsd:
    build:
      context: ./gpsd/
    ports:
      - "2947:2947"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"